# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 编译产物

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        uses: pnpm/action-setup@v4.1.0
        with:
          # Version of pnpm to install
          version: 10.10.0
          # If specified, run `pnpm install`
          run_install: true
      - name: 安装 依赖
        run: pnpm install

      # - name: 测试
      #   run: pnpm test

      - name: 编译
        run: pnpm run build --if-present

