# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 编译产物

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20.19.3
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.3
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.10.0
          run_install: true

      - name: Build
        run: pnpm run build --if-present

      # - name: Test
      #   run: pnpm test
